spring:
  application:
    name: 04-Welcome-API
  boot:
    admin:
      client:
        url: http://localhost:1111
management:
  endpoint:
    web:
      exposure:
        include: '*' 
  
    
      