spring:
  application:
    name: 07-Cloud_Config_Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/softwaresuchitraind/configuration_properties
          
server:
  port: 9093
  

  