spring:
  application:
    name: 06-API_Gateway
  cloud:
    gateway:
      routes:
      - id: api-1
        uri: lb://04-Welcome-API
        predicates:
        - Path=/welcome
      - id: api-2
        uri: lb://05-Greet-Service
        predicates:
        - Path=/greet
server:
  port: 3333
  
